FROM ubuntu:22.04
MAINTAINER expressliberate@gmail.com

# Instalando dependencias
RUN sudo apt update 
RUN sudo apt dist-upgrade -y
RUN sudo apt install -y wget build-essential subversion

# Baixe o asterisk 18 e descompacte entre as pastas
RUN wget http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-18-current.tar.gz && tar zxf asterisk-18-current.tar.gz
RUN cd asterisk-18*./

# Suporte para arquivos MP3 no Asterisk, baixe as fontes para compilar os módulos mp3 do asterisk
RUN sudo contrib/scripts/get_mp3_source.sh

# Instalando as dependencias para a compilação do asterisk
RUN sudo contrib/scripts/install_prereq install

# Compilação do codigo fonte 

# Configure o arquivo de instalação

RUN sudo ./configure
RUN make -j$(nproc) menuselect.makeopts
RUN menuselect/menuselect \
                          --disable BUILD_NATIVE \
                          --enable cdr_csv \
                          --enable chan_sip \
                          --enable res_snmp \
                          --enable res_http_websocket \
                      menuselect.makeopts \

# Conpile e instale o asterisk
RUN sudo make
RUN sudo make install

# Gerando os arquivos de configuração básicos e o script de inicialização do asterisk como um serviço do sistema
RUN sudo make basic-pbx
RUN sudo make config

# Inicialização do serviço asterisk no sistema
# Inicie o servoço do asterisk e habilite-o para que seja inicializado junto com o sistema operacional
RUN sudo systemctl start asterisk
RUN sudo systemctl enable asterisk

# Iniciando o asterisk como usuário asterisk
USER asterisk
CMD /usr/sbin/asterisk -rvvvvv

